name: Main

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  mac-build:
    runs-on: macos-latest

    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install Qt
        run: brew update && brew install qt@5

      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 0
          submodules: recursive

      - run: echo "basename=bsnes-plus-${{env.GITHUB_REF_SLUG}}-mac" >> $GITHUB_ENV
        name: Set variables

      - name: Build wasm3
        run: |
          cd external/wasm3
          mkdir build
          cd build
          cmake ..
          make -j2

      - name: Build bsnes-plus
        run: |
          cd bsnes
          make qtpath=/usr/local/opt/qt@5

      # cross-platform tar.gz creator:
      - name: Create ${{env.basename}}.tar.gz
        run: >
          go run
          .github/scripts/tar.go
          -z
          -o ${{env.basename}}.tar.gz
          bsnes+.app/

      - uses: actions/upload-artifact@v1
        name: Upload artifact
        with:
          name: ${{env.basename}}.tar.gz
          path: ${{github.workspace}}/${{env.basename}}.tar.gz

  windows-build:
    runs-on: windows-latest

    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set variables
        run: |
          echo "basename=bsnes-plus-${{env.GITHUB_REF_SLUG}}-windows" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Build wasm3
        run: |
          cd external/wasm3
          cmake -G "MinGW Makefiles" -B build
          cmake --build build

      - name: Build bsnes-plus
        run: |
          cd bsnes

          mingw32-make -j8 build platform=win profile=performance version=${{env.GITHUB_REF_SLUG}}
          mingw32-make -j8 platform=win version=${{env.GITHUB_REF_SLUG}}

          cd out

          move ..\..\snesfilter\snesfilter.dll
          move ..\..\snesreader\snesreader.dll
          move ..\..\snesmusic\snesmusic.dll
          move ..\..\supergameboy\supergameboy.dll

          mkdir bsxdat
          copy ..\data\bsxdat bsxdat

          copy "..\..\external\qt\mingw-w64\bin\*.dll"
          xcopy /E "..\..\external\qt\mingw-w64\plugins"

          copy "%MINGW_PATH%\libgcc_s_seh-1.dll"
          copy "%MINGW_PATH%\libgomp-1.dll"
          copy "%MINGW_PATH%\libstdc++-6.dll"
          copy "%MINGW_PATH%\libwinpthread-1.dll"

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.basename}}.zip
          path: ${{github.workspace}}\bsnes\out
